name: forge2d_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  characters: ^1.4.1
  flame: ^1.36.0
  flame_forge2d: ^0.19.2+5
  flame_kenney_xml: ^0.1.2
  flutter:
    sdk: flutter
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
